### ISSUE TITLE
We seem to be having deploy issues

### ISSUE THREAD

**Issue by aarongustafson** [tobymackenzie/10k-gol.site#1]
Take a look: https://conway-s-game-of-life-10kapart2016.azurewebsites.net/

Not sure what would be causing this.

**Comment by aarongustafson** [comment]
Oh wait, I know: We need it to be the master branch.

**Comment by tobymackenzie** [comment]
okay, I merged dist into master

**Comment by aarongustafson** [comment]
Trying to deploy now. I’ll let you know.

**Comment by aarongustafson** [comment]
Still running into problems. I have one of our server admins looking into it.

**Comment by tobymackenzie** [comment]
It uses composer purely for autoloading.  I've never deployed on WIndows or IIS.  I use some `$_SERVER` variables, including `REQUEST_URI` (in `src/HTTP.php`).  Might I have to use `PHP_SELF` instead (per [this](https://davidwalsh.name/iis-php-server-request_uri))?  I use forward slashes for paths, but I believe PHP takes care of that.  I pull in various files via `require` / `include` as well as `file_get_contents()` (for inlining css / js).  Would any of that cause problems?
